version: "3"
services:
  database:
    image: mysql
    container_name: order_db
    environment:
      - MYSQL_DATABASE=order_db
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=order
      - MYSQL_PASSWORD=order
      - TZ='Asia/Seoul'
    ports:
      - 3306:3306
    volumes:
      - ./db/order/data:/var/lib/mysql
    networks:
      - order_network
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    links:
      - database
    ports:
      - 8080:8080
    container_name: order_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/order_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - order_network
#  redis:
#    image: redis:alpine
#    command: redis-server --port 6379
#    container_name: order_service_redis
#    hostname: order_service_redis
#    labels:
#      - "name=redis"
#      - "mode=standalone"
#    ports:
#      - 6379:6379

networks:
  order_network: